### ISSUE TITLE
Permission denied when pushing

### ISSUE THREAD

**Issue by eloyesp** [mnalis/android-wifi-upgrade#1]
I get an error when pushing the generated file.

(I've enabled root access on ADB with no luck.)

```
adb push WifiConfigStore.xml /data/misc/wifi/WifiConfigStore.xml
adb: error: stat failed when trying to push to /data/misc/wifi/WifiConfigStore.xml: Permission denied
```

**Comment by mnalis** [comment]
Can you send me an output of following commands (you may need to run them one by one, not copy/pasting whole block):

```
adb root
adb shell id
adb shell getenforce
adb shell ls -ldZ / /data /data/misc /data/misc/wifi /data/misc/wifi/WifiConfigStore.xml
adb shell cat /proc/mounts

```

Also, what android version is that?

**Comment by eloyesp** [comment]
It seems that I've forgot the `adb root` part, I've tried again and it is working now. Thank you (I've collected +100 networks that I have available now :smile: ).

[Here is the output anyway](https://pastebin.com/4QGHPkAt)
